### ISSUE TITLE
Allow execution of shell_run_command in task

### ISSUE THREAD

**Issue by fkromer** [PrefectHQ/prefect-shell#30]
ATM shell commands can be invoked in flows only, not in tasks (`RuntimeError: Tasks cannot be run from within tasks. Did you mean to call this task in a flow?`). Would be great to be able to invoke shell commands in tasks as well.

**Comment by ahuang11** [comment]
Hi! You can invoke the underlying function of `shell_run_command` by doing `shell_run_command.fn(*args, **kwargs)`. Let me know if that works!

**Comment by fkromer** [comment]
Right now it's not working yet. I'm getting `RuntimeWarning: coroutine 'shell_run_command' was never awaited
  shell_run_command.fn(command=cli_command, return_all=True)`.

**Comment by ahuang11** [comment]
Are you executing that within a notebook? If so, you simply need `await shell_run_command.fn()`

However, it's recommended that you put it within another task/flow.
```
@flow
def test_flow():
   return shell_run_command.fn(...)

**Comment by madkinsz** [comment]
If calling the underlying `fn` you'll bypass our sync-async compatibility machinery that is used for tasks.

**Comment by fkromer** [comment]
@madkinsz This means I've to stick to shell command calls in flows for now, right?

**Comment by desertaxle** [comment]
@fkromer you can use shell commands in tasks with the `.fn()` function, but the tasks will need to be `async` and you'll need to `await` the `.fn()` call. Fortunately, `async` tasks can be called from synchronous flows, so you should be able to isolate the asynchronous code to only a portion of of your flow.

**Comment by desertaxle** [comment]
I believe that this issue has been resolved. Feel free to reopen if that is not the case!
