### ISSUE TITLE
Allow command to be passed as a list, and allow cwd to be passed in a platform-agnostic way

### ISSUE THREAD

**Issue by matthewgdv** [PrefectHQ/prefect-shell#38]
Since these changes are actually quite simple I'd be happy to implement them myself if the maintainer can tell me in advance that they'd be happy to merge the following PR.

Basically, I'd like to update the signature of `shell_run_command` to:

```python
async def shell_run_command(
    command: Union[List[str], str],
    env: Optional[dict] = None,
    helper_command: Optional[str] = None,
    shell: str = "bash",
    return_all: bool = False,
    stream_level: int = logging.INFO,
    cwd: Union[str, bytes, PathLike, None] = None,
) -> Union[List, str]:
```

And:
 - pass the `cwd` argument through to `anyio.open_process(cwd=)` (removing the need to use a shell-specific helper-command for the extremely common use-case of setting a working directory)
 - use `subprocess.list2cmdline()` to convert the `command` argument to a string if it is a list (this avoids unnecessary string-formatting operations and removes the need for the user to concern themselves with error-prone character escaping)

**Comment by ahuang11** [comment]
That'd be great, thanks! Would you mind creating two separate PRs for those?

**Comment by matthewgdv** [comment]
Thanks for the quick reply! I've opened the first PR now.

And good point, I hadn't actually seen that `anyio.open_process()` accepts a sequence of `str` directly as the command. Definitely no need to use `subprocess.list2cmdline()` in that case. I assume that since `anyio` has windows support we can trust it to handle windows-specific character escaping and any edge-cases upstream.

**Comment by ahuang11** [comment]
Maybe we need to [drop this line](https://github.com/PrefectHQ/prefect-shell/blob/main/prefect_shell/commands.py#L79-L80) in regards to list2cmdline?

**Comment by ahuang11** [comment]
Allow anyio to handle this in https://github.com/PrefectHQ/prefect-shell/pull/47
