### ISSUE TITLE
Breaking changes from 0.1.0 to 0.1.1

### ISSUE THREAD

**Issue by Trymzet** [PrefectHQ/prefect-shell#49]
Hi, you introduced some breaking changes in 0.1.1 (eg. changed the function to task, removed the `logger` param). It's great to see this collection worked on. My only ask is, could you please adhere to semantic versioning? Unfortunately due to this I had to pin this dependency down to the patch version.

**Comment by ahuang11** [comment]
Thank you for bringing this to our attention. I will be closing this issue, but feel free to re-open if you have further feedback for us!
