### ISSUE TITLE
Allow to rename task name

### ISSUE THREAD

**Issue by Hongbo-Miao** [PrefectHQ/prefect-shell#60]
I have many `shell_run_command` run concurrently. I am hoping to rename them to help locate on Prefect Radar.

It would be great to have something like

```py
shell_run_command(
    name=f"copy_{source}_to_{destination}",  # This parameter does not exist currently
    command=f"rclone copy --progress {source} {destination}",
)
```

This screenshot I only show two tasks.

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/3375461/209808695-80c3863a-a2c3-4b2e-940e-58621b175cad.png">

Allow renaming task name would be very helpful to locate the one I hope to check on Prefect Radar. Thanks! 😃

**Comment by desertaxle** [comment]
Hey @Hongbo-Miao! You can use the `.with_options` method that is available on all tasks to customize the name or other attributes of the task. Here's a link to an example of how to use `.with_options` in the Prefect documentation: https://docs.prefect.io/collections/usage/?h=with_options#customizing-tasks-and-flows-from-a-collection.

**Comment by Hongbo-Miao** [comment]
Thanks @desertaxle for the link!

Just post the final solution to save time for future people.

As originally I was using 

```py
shell_run_command(command=f"rclone copy --progress {src} {dest}").with_options(
    name=f"copy_{source}_to_{destination}"
)
```
which is wrong.

The correct way to do it is

```py
rclone = shell_run_command.with_options(name=f"copy_{source}_to_{destination}")
rclone(command=f"rclone copy --progress {src} {dest}")
```
